// EXPORT SMOKE CHECK — generated by export-judges.py. Starts the built server on a private port and
// performs read-only requests. It never sends a conversation turn, so no company memory or sponsor service is changed.
import { spawn } from 'node:child_process';
import { resolve } from 'node:path';
const project = resolve(import.meta.dirname, '..');
const output = process.env.TRU_PLAN_OUTPUT ?? resolve(project, 'run');
import { createServer } from 'node:net';
// Pick a port that is free right now, so another process on a fixed port can never answer for this server.
const port = await new Promise<number>((res, rej) => { const probe = createServer(); probe.listen(0, '127.0.0.1', () => { const p = (probe.address() as { port: number }).port; probe.close(() => res(p)); }); probe.on('error', rej); });
const child = spawn('node', [resolve(output, 'dist/server.js')], { env: { ...process.env, TRU_PLAN_OUTPUT: output, TRU_SOURCE: project, TRU_PLAN_PORT: String(port) }, stdio: ['ignore', 'pipe', 'pipe'] });
let log = ''; child.stdout.on('data', d => { log += d; }); child.stderr.on('data', d => { log += d; });
const base = `http://127.0.0.1:${port}`;
let ok = false;
for (let i = 0; i < 40 && !ok; i++) { await new Promise(r => setTimeout(r, 250)); if (log.includes(`http://127.0.0.1:${port}`)) { try { ok = (await fetch(`${base}/talk`)).status === 200; } catch {} } if (child.exitCode !== null) break; }
const results: Record<string, number | string> = {};
try {
  if (!ok) throw new Error('server did not answer on /talk: ' + log.slice(-400));
  for (const path of ['/', '/talk', '/talk.js', '/talk.css', '/api/company', '/evidence/build-plan', '/evidence/full-flow-verification', '/evidence/unknown', '/.env', '/api/snapshot']) results[path] = (await fetch(base + path)).status;
  results['POST /api/conversation/new (foreign origin)'] = (await fetch(`${base}/api/conversation/new`, { method: 'POST', headers: { Origin: 'https://outside.example', 'Content-Type': 'application/json' }, body: '{}' })).status;
  results['/api/conversation/progress?id=not-a-uuid'] = (await fetch(`${base}/api/conversation/progress?id=not-a-uuid`)).status;
  results['company.sampleData'] = String((await (await fetch(`${base}/api/company`)).json()).data.sampleData);
  const sponsorSource = await (await import('node:fs/promises')).readFile(resolve(project, 'src/sponsor-evidence.ts'), 'utf8');
  const linkIds = new Set([...sponsorSource.matchAll(/receipt:\s*'([a-z0-9-]+)'/g)].map(m => m[1]));
  for (const block of sponsorSource.matchAll(/receipts:\s*\[([\s\S]*?)\]/g)) for (const m of block[1].matchAll(/id:\s*'([a-z0-9-]+)'/g)) linkIds.add(m[1]);
  for (const id of linkIds) results[`/evidence/${id} (sponsor link)`] = (await fetch(`${base}/evidence/${id}`)).status;
} finally { child.kill('SIGTERM'); }
console.log(JSON.stringify({ port, results, cloudCalls: 0, conversationTurns: 0 }, null, 2));
const expected: Record<string, number | string> = { '/': 200, '/talk': 200, '/talk.js': 200, '/talk.css': 200, '/api/company': 200, '/evidence/build-plan': 200, '/evidence/full-flow-verification': 200, '/evidence/unknown': 404, '/.env': 404, '/api/snapshot': 200, 'POST /api/conversation/new (foreign origin)': 403, '/api/conversation/progress?id=not-a-uuid': 400, 'company.sampleData': 'true' };
for (const k of Object.keys(results)) if (k.endsWith('(sponsor link)')) expected[k] = 200;
const bad = Object.entries(expected).filter(([k, v]) => results[k] !== v);
if (bad.length) { console.error('Smoke check failed: ' + JSON.stringify(bad)); process.exit(1); }
console.log('Smoke check passed.');
