import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdir,mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import {GptLiveServer,gptLiveAllowance,liveSpokenText,type GptLiveOptions,type LiveStart} from '../src/gpt-live.ts';
import {LiveEventBridge,GptLiveBrowser,waitForLiveIce} from '../src/gpt-live-browser.ts';
const base=process.env.TRU_TEST_RUNS??`${process.cwd()}/run/gpt-live-tests`;
const clock=Date.parse('2026-09-11T21:36:00Z');
const allowance={schema:1,enabled:true,model:'gpt-live-1',gatewayBase:'https://gateway.ai.cloudflare.com/v1/'+'a'.repeat(32)+'/test/openai',validUntil:'2026-09-11T22:00:00Z',creditVerifiedAt:'2026-09-11T21:35:00Z',availableCreditCents:100,autoRefillOff:true,maxCostCents:45,maxSessions:3,maxSessionSeconds:180};
async function setup(extra:Partial<GptLiveOptions>={}){await mkdir(base,{recursive:true});const dir=await mkdtemp(base+'/guard-');await writeFile(dir+'/gpt-live-allowance.json',JSON.stringify(allowance));const requests:{url:string;body:any}[]=[],scheduled:{fn:()=>void;ms:number}[]=[],turns:any[]=[];
 const options:GptLiveOptions={dataDir:dir,now:()=>clock,token:()=>'INJECTED_NOT_A_KEY',schedule:(fn,ms)=>{scheduled.push({fn,ms});return ()=>{};},conversationTurn:async input=>{turns.push(input);return {reply:'The sample quote is ready for review.'};},fetchImpl:async(url,init)=>{const ledger=JSON.parse(await readFile(dir+'/gpt-live-ledger.json','utf8'));assert.ok(ledger.attempts.length>0);requests.push({url:String(url),body:init?.body?JSON.parse(String(init.body)):undefined});assert.equal((init?.headers as any)['cf-aig-authorization'],'Bearer INJECTED_NOT_A_KEY');assert.equal(init?.redirect,'error');return String(url).endsWith('/hangup')?new Response(null,{status:200}):Response.json({session:{id:'live_injected'},transport:{type:'webrtc',sdp:'v=0\r\nanswer'}});},...extra};
 return {dir,requests,scheduled,turns,server:new GptLiveServer(options),options,clean:()=>rm(dir,{recursive:true,force:true})};}
const offer={sdp:'v=0\r\noffer',conversationId:'conversation_1'};
const transcript=[{role:'user' as const,delta:'Review 140 shirts.',startMs:0,endMs:900}];
test('disabled, malformed allowance, expired credits, foreign gateway and invalid optional limit make zero requests',async()=>{for(const a of [null,{enabled:false},{...allowance,creditVerifiedAt:'2026-09-11T20:00:00Z'},{...allowance,validUntil:'invalid'},{...allowance,gatewayBase:'https://evil.invalid'},{...allowance,maxSessionSeconds:0}]){const f=await setup();try{if(a===null)await rm(f.dir+'/gpt-live-allowance.json');else await writeFile(f.dir+'/gpt-live-allowance.json',JSON.stringify(a));await assert.rejects(f.server.create(offer));assert.equal(f.requests.length,0);}finally{await f.clean();}}});
test('reserves before create, fixes voice/model/client mode, exposes no token and arms 180 second server hangup',async()=>{const f=await setup();try{const s=await f.server.create(offer);assert.equal(s.voice,'willow');assert.equal(f.scheduled[0].ms,180000);assert.equal(f.requests[0].body.session.model,'gpt-live-1');assert.deepEqual(f.requests[0].body.session.delegation,{type:'client'});assert.equal(f.requests[0].body.session.store,false);assert.ok(!JSON.stringify(s).includes('INJECTED'));assert.equal(JSON.parse(await readFile(f.dir+'/gpt-live-ledger.json','utf8')).attempts[0].reservedCents,18);await f.server.close(s.attemptId);assert.ok(f.requests[1].url.endsWith('/live_injected/hangup'));const ledger=JSON.parse(await readFile(f.dir+'/gpt-live-ledger.json','utf8'));assert.equal(ledger.attempts[0].hangup,'accepted');assert.equal(ledger.attempts[0].status,'ambiguous');}finally{await f.clean();}});
test('ambiguous creation remains reserved and never retries or leaks provider diagnostic',async()=>{let calls=0;const f=await setup({fetchImpl:async()=>{calls++;throw new Error('SECRET_PROVIDER_BODY');}});try{await assert.rejects(f.server.create(offer),e=>!String(e).includes('SECRET'));await assert.rejects(f.server.create(offer),/unconfirmed/);assert.equal(calls,1);assert.equal(JSON.parse(await readFile(f.dir+'/gpt-live-ledger.json','utf8')).attempts[0].status,'ambiguous');}finally{await f.clean();}});
test('budget refusal and simultaneous attempts cannot exceed reservation',async()=>{const f=await setup();try{await writeFile(f.dir+'/gpt-live-allowance.json',JSON.stringify({...allowance,maxCostCents:2}));await assert.rejects(f.server.create(offer),/balance/);assert.equal(f.requests.length,0);await writeFile(f.dir+'/gpt-live-allowance.json',JSON.stringify(allowance));const results=await Promise.allSettled([f.server.create(offer),f.server.create(offer)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(f.requests.length,1);}finally{await f.clean();}});
test('delegation calls only supplied conversation callback, reuses duplicate, rejects stale/prototype and no transcript',async()=>{const f=await setup();try{const s=await f.server.create(offer),d={attemptId:s.attemptId,delegationId:'item_1',offsetMs:1000,transcript};assert.equal((await f.server.delegate(d)).content,'The sample quote is ready for review.');assert.equal((await f.server.delegate(d)).reused,true);assert.equal(f.turns.length,1);assert.equal(f.turns[0].conversationId,'conversation_1');assert.equal(f.turns[0].message,'Review 140 shirts.');await assert.rejects(f.server.delegate({...d,delegationId:'item_2'}),/Stale/);await assert.rejects(f.server.delegate({...d,delegationId:'__proto__',offsetMs:1100}));await assert.rejects(f.server.delegate({...d,delegationId:'item_3',offsetMs:1200,transcript:[]}));}finally{await f.clean();}});
test('closure requires matching final session event; usage snapshots are cumulative and provenance explicit',async()=>{const f=await setup();try{const s=await f.server.create(offer);await f.server.observe({attemptId:s.attemptId,event:{type:'session.usage.updated',usage:{seconds:12}}});await assert.rejects(f.server.observe({attemptId:s.attemptId,event:{type:'session.closed',session:{id:'wrong'},usage:{seconds:13}}}));await f.server.observe({attemptId:s.attemptId,event:{type:'session.closed',session:s.session,usage:{seconds:13},reason:'close_requested'}});await assert.rejects(f.server.create(offer),/unconfirmed/);await f.server.close(s.attemptId);const a=JSON.parse(await readFile(f.dir+'/gpt-live-ledger.json','utf8')).attempts[0];assert.deepEqual(a.usage,{seconds:13,final:true,source:'browser-session-event',reason:'close_requested'});assert.equal(a.status,'closed');}finally{await f.clean();}});
test('restart recovery hangs up known session, does not create a replacement',async()=>{const f=await setup();try{await f.server.create(offer);const recovered=new GptLiveServer(f.options);await recovered.recover();assert.equal(f.requests.length,2);assert.ok(f.requests[1].url.endsWith('/hangup'));await assert.rejects(recovered.create(offer),/unconfirmed/);}finally{await f.clean();}});
test('speech append uses a conservative UTF8 bound including non-English output',()=>{assert.ok(Buffer.byteLength(liveSpokenText('🙂'.repeat(500)))<=480);});
const session:LiveStart={attemptId:'attempt_1',session:{id:'live_test'},transport:{type:'webrtc',sdp:'v=0'},expiresAt:'2026-09-11T22:00:00Z',maxSeconds:180,voice:'willow'};
test('event bridge collects exact fragments, never treats transcript as a turn, suppresses duplicate and corrected late result',async()=>{const sent:any[]=[],delegations:any[]=[];let complete!:(v:any)=>void;const bridge=new LiveEventBridge(session,{delegate:async d=>{delegations.push(d);return new Promise(r=>{complete=r;});},observe:async()=>{}},e=>sent.push(e),()=>{});
 await bridge.event({type:'session.started',session:session.session});await bridge.event({type:'session.input_transcript.delta',delta:'Review ',start_ms:0,end_ms:200});await bridge.event({type:'session.input_transcript.delta',delta:'140 shirts.',start_ms:200,end_ms:900});assert.equal(delegations.length,0);
 const event={type:'session.delegation.created',offset_ms:1000,delegation:{id:'item_x',target:'client'}};const pending=bridge.event(event);await bridge.event(event);assert.equal(delegations.length,1);assert.equal(delegations[0].transcript.map((x:any)=>x.delta).join(''),'Review 140 shirts.');await bridge.event({type:'session.input_transcript.delta',delta:'Actually 150.',start_ms:1100,end_ms:1500});complete({content:'Old result',delegationId:'item_x'});await pending;assert.equal(sent.length,0);
});
test('bridge returns commentary using original delegation id, handles session.closed only after stopping',async()=>{const sent:any[]=[],seen:any[]=[],final:boolean[]=[];const bridge=new LiveEventBridge(session,{delegate:async d=>({content:'Verified reply',delegationId:d.delegationId}),observe:async e=>{seen.push(e);}},e=>sent.push(e),v=>final.push(v));await bridge.event({type:'session.started',session:session.session});await bridge.event({type:'session.input_transcript.delta',delta:'Review',start_ms:0,end_ms:100});await bridge.event({type:'session.delegation.created',offset_ms:200,delegation:{id:'item_exact',target:'client'}});assert.equal(sent[0].type,'session.commentary.append');assert.equal(sent[0].delegation_id,'item_exact');bridge.stop();await bridge.event({type:'session.closed',session:{id:'wrong'},usage:{seconds:1}});assert.equal(final.length,0);await bridge.event({type:'session.closed',session:session.session,usage:{seconds:3}});assert.deepEqual(final,[true]);assert.equal(seen.length,1);});
test('overlapping approval fragment is consumed only after its complete interval, never repeated',async()=>{const f=await setup();try{const s=await f.server.create(offer),d={attemptId:s.attemptId,delegationId:'first',offsetMs:1000,transcript:[{role:'user' as const,delta:'approve',startMs:900,endMs:1200}]};await assert.rejects(f.server.delegate(d),/No usable/);await f.server.delegate({...d,delegationId:'second',offsetMs:1400});await assert.rejects(f.server.delegate({...d,delegationId:'third',offsetMs:1600}),/No usable/);assert.equal(f.turns.length,1);}finally{await f.clean();}});
test('deadline hangup proceeds while ledger lock is held; recovery retries a requested known hangup',async()=>{const f=await setup();try{const s=await f.server.create(offer);await writeFile(f.dir+'/gpt-live.lock','held');f.scheduled[0].fn();await new Promise(r=>setTimeout(r,10));assert.equal(f.requests.filter(x=>x.url.endsWith('/hangup')).length,1);await rm(f.dir+'/gpt-live.lock');await new Promise(r=>setTimeout(r,40));const path=f.dir+'/gpt-live-ledger.json',ledger=JSON.parse(await readFile(path,'utf8'));ledger.attempts[0].hangup='requested';await writeFile(path,JSON.stringify(ledger));await new GptLiveServer(f.options).recover();assert.equal(f.requests.filter(x=>x.url.endsWith('/hangup')).length,2);}finally{await f.clean();}});

test('microphone refusal makes no session request and releases the peer',async()=>{let created=0,closed=0;const statuses:string[]=[];const peer={addEventListener(){},close(){closed++;}};const browser=new GptLiveBrowser({audio:{srcObject:null} as unknown as HTMLAudioElement,peerFactory:()=>peer as unknown as RTCPeerConnection,getUserMedia:async()=>{throw Error('denied');},createSession:async()=>{created++;return session;},delegate:async()=>({content:'',delegationId:''}),observe:async()=>{},closeSession:async()=>{},onStatus:s=>statuses.push(s)});await browser.start('conversation');assert.equal(created,0);assert.equal(closed,1);assert.equal(statuses.at(-1),'error');});

test('funded-balance-only default removes180seconds/45c/3session limits and retains30second close reserve',async()=>{const f=await setup();try{const a:any={...allowance,availableCreditCents:1000};delete a.maxCostCents;delete a.maxSessions;delete a.maxSessionSeconds;await writeFile(f.dir+'/gpt-live-allowance.json',JSON.stringify(a));const s=await f.server.create(offer);assert.equal(s.maxSeconds,11970);assert.equal(f.scheduled[0].ms,11970000);assert.equal(JSON.parse(await readFile(f.dir+'/gpt-live-ledger.json','utf8')).attempts[0].reservedCents,1000);assert.equal(f.requests[0].body.session.max_duration,undefined);}finally{await f.clean();}});
test('refill enabled or unverified excess funds refuse creation',async()=>{for(const patch of [{autoRefillOff:false},{availableCreditCents:1001}]){const f=await setup();try{await writeFile(f.dir+'/gpt-live-allowance.json',JSON.stringify({...allowance,...patch}));await assert.rejects(f.server.create(offer));assert.equal(f.requests.length,0);}finally{await f.clean();}}});
class FakePeer extends EventTarget {iceGatheringState:RTCIceGatheringState='gathering';connectionState:RTCPeerConnectionState='new';localDescription:any={type:'offer',sdp:'v=0 gathered'};closed=false;channel=Object.assign(new EventTarget(),{readyState:'open',send:(_v:string)=>{},close:()=>{}});async createOffer(){return {type:'offer',sdp:'v=0 incomplete'};}async setLocalDescription(_v:unknown){}async setRemoteDescription(_v:unknown){}addTrack(){}createDataChannel(){return this.channel;}close(){this.closed=true;}}
test('ICE gathers before provider creation and sends final localDescription; pagehide closes and missing finalevent stays unconfirmed',async()=>{const peer=new FakePeer(),lifecycle=new EventTarget(),statuses:string[]=[],created:any[]=[],closed:string[]=[];let trackStopped=0;const browser=new GptLiveBrowser({audio:{srcObject:null} as any,peerFactory:()=>peer as any,getUserMedia:async()=>({getTracks:()=>[{stop:()=>{trackStopped++;}}],getAudioTracks:()=>[]} as any),lifecycleTarget:lifecycle,closeTimeoutMs:5,createSession:async input=>{created.push(input);return {...session,expiresAt:new Date(Date.now()+600000).toISOString()};},delegate:async d=>({delegationId:d.delegationId,content:''}),observe:async()=>{},closeSession:async id=>{closed.push(id);},onStatus:s=>statuses.push(s)});const start=browser.start('conversation');await new Promise(r=>setTimeout(r,1));assert.equal(created.length,0);peer.iceGatheringState='complete';peer.dispatchEvent(new Event('icegatheringstatechange'));await start;assert.equal(created[0].sdp,'v=0 gathered');lifecycle.dispatchEvent(new Event('pagehide'));await new Promise(r=>setTimeout(r,15));assert.deepEqual(closed,['attempt_1']);assert.equal(statuses.at(-1),'unconfirmed');assert.ok(trackStopped>0);assert.equal(peer.closed,true);});
test('ICE timeout and abort reject before any billable request',async()=>{const peer=new FakePeer();await assert.rejects(waitForLiveIce(peer as any,new AbortController().signal,2),/timed out/);const ctrl=new AbortController();const pending=waitForLiveIce(peer as any,ctrl.signal);ctrl.abort();await assert.rejects(pending,/stopped/);});
test('delegation/commentary waits for matching session.started and deduplicates transcript events',async()=>{const sent:any[]=[],calls:any[]=[];const bridge=new LiveEventBridge(session,{delegate:async d=>{calls.push(d);return {delegationId:d.delegationId,content:'Confirmed'};},observe:async()=>{}},e=>sent.push(e),()=>{});const input={type:'session.input_transcript.delta',event_id:'fragment_1',delta:'Review',start_ms:0,end_ms:100};await bridge.event(input);await bridge.event(input);await bridge.event({type:'session.delegation.created',event_id:'event_1',offset_ms:200,delegation:{id:'item_1',target:'client'}});assert.equal(calls.length,0);assert.equal(sent.length,0);await bridge.event({type:'session.started',session:{id:'wrong'}});assert.equal(calls.length,0);await bridge.event({type:'session.started',session:session.session});assert.equal(calls.length,1);assert.equal(calls[0].transcript.length,1);assert.equal(sent[0].delegation_id,'item_1');});
