// EXPORT TEST SUBSET — generated by export-judges.py from tests/control-room.test.ts in the source.
// Kept: every test of the conversation, memory, company-data and Hotdata-worker logic. Dropped: tests of the
// private planning checklist, telemetry summaries and worker monitor, which are not part of this submission.
import {sanitizeIntent} from '../src/conversation-model.ts';
import {beginProgress,progressSnapshot} from '../src/live-progress.ts';
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import { resolve } from 'node:path';
import { request } from 'node:http';
import { StateStore, StateError } from '../src/state.ts';
import { makeServer } from '../src/server.ts';
import { TASKS } from '../src/model.ts';
import { summarizeTelemetry, redact } from '../src/sources.ts';
import { currentMonitor } from '../src/workers.ts';
import { initialRehearsal, sampleProposal, reviewSample, approveSample, replaySample, invalidateSample } from '../src/rehearsal-model.ts';
import { applyIntent, newConversation, refreshCompanyContext, isCurrentPacket, shipmentPolicyInstruction, historicalShipmentPolicyIndexes, splitForbidden } from '../src/conversation-model.ts';
import { CompanyWorkspace, validateCompany } from '../src/company-workspace.ts';
import { hotdataRows, runDataWorkers } from '../src/data-workers.ts';
import { reviewFingerprint, hasCurrentCloudReview } from '../src/approval-proof.ts';
const base = process.env.TRU_TEST_RUNS ?? resolve(process.env.TRU_PLAN_OUTPUT ?? 'run', 'test-runs');

async function temporary() { await mkdir(base, { recursive: true }); return mkdtemp(`${base}/run-`); }

test('sample decision respects budget and deadline and refuses an unfulfillable approval', () => {
  const first = sampleProposal(150, 180000);
  assert.deepEqual(first.options.map(option => option.totalCents), [165000, 195000, 175000]);
  assert.equal(first.options[0].withinBudget, true);
  assert.equal(first.options[0].onTime, false);
  assert.equal(first.chosen?.id, 'split');
  const impossible = reviewSample(initialRehearsal(), 150, 100000);
  assert.equal(impossible.proposal?.chosen, null);
  assert.throws(() => approveSample(impossible), /feasible reviewed proposal/);
  assert.throws(() => sampleProposal(150.5, 180000));
  assert.throws(() => sampleProposal(201, 180000));
  assert.throws(() => sampleProposal(150, NaN));
});

test('changing a sample preserves prior context but cannot reuse its approval for a new quantity', () => {
  let state = reviewSample(initialRehearsal(), 150, 180000);
  state = approveSample(state);
  assert.equal(state.approved?.quantity, 150);
  const next = replaySample(state);
  assert.equal(next.proposal?.chosen?.totalCents, 163000);
  assert.equal(next.proposal?.quantity, 140);
  assert.equal(next.approved, null);
  assert.equal(next.memory[0].quantity, 150);
  assert.equal(state.approved?.quantity, 150);
  const edited = invalidateSample(state);
  assert.equal(edited.proposal, null);
  assert.equal(edited.approved, null);
  assert.throws(() => approveSample(edited));
  assert.throws(() => replaySample(initialRehearsal()));
});

test('a cloud-verified proposal cannot approve a changed order, policy, price or result',async()=>{
  const company=validateCompany(JSON.parse(await readFile('fixtures/company.json','utf8')));
  let state=applyIntent(newConversation('cloud-approved'),{action:'review',quantity:150},'150 shirts',company).state;
  state.cloudReview={fingerprint:reviewFingerprint(state,company),receiptId:'verified-receipt'};
  assert.equal(hasCurrentCloudReview(state,company),true);
  const approved=applyIntent(state,{action:'approve'},'Yes approve it',company).state;
  assert.equal(hasCurrentCloudReview(approved,company),true);
  assert.equal(hasCurrentCloudReview({...state,quantity:140},company),false);
  assert.equal(hasCurrentCloudReview({...state,notes:['Never split shipments.']},company),false);
  assert.equal(hasCurrentCloudReview(state,{...company,stock:{...company.stock,unitCents:901}}),false);
  const altered=structuredClone(state);altered.rehearsal.proposal!.chosen!.totalCents=1;
  assert.equal(hasCurrentCloudReview(altered,company),false);
  const noted=applyIntent(approved,{action:'remember',memoryNote:'Never split shipments.'},'Never split shipments.',company).state;
  assert.equal(noted.rehearsal.proposal,null);assert.equal(noted.rehearsal.approved,null);
  assert.equal(hasCurrentCloudReview(noted,company),false);
  assert.equal(applyIntent(noted,{action:'approve'},'Yes approve',company).state.rehearsal.approved,null);
  assert.equal(applyIntent(noted,{action:'draft'},'Write the packet',company).draft,null);
});

test('conversation approval is explicit and amendments cannot inherit it',()=>{
  let state=applyIntent(newConversation('test'),{action:'review',quantity:150},'150 shirts').state;
  for(const message of ['Do not approve','Can I approve?','No','hold it'])assert.equal(applyIntent(state,{action:'approve'},message).state.rehearsal.approved,null);
  state=applyIntent(state,{action:'approve'},'Yes, approve it').state;
  assert.equal(state.rehearsal.approved?.totalCents,175000);
  const amended=applyIntent(state,{action:'draft',quantity:140},'Draft it for 140 shirts');
  assert.equal(amended.state.rehearsal.proposal?.chosen?.totalCents,163000);
  assert.equal(amended.state.rehearsal.approved,null);assert.equal(amended.draft,null);
});

test('preparing or publishing a changed order cannot silently use the old approval',()=>{
  let state=applyIntent(newConversation('publish'),{action:'review',quantity:140},'140 shirts').state;
  state=applyIntent(state,{action:'approve'},'Approve').state;
  for(const action of ['launch','publish'] as const){
    assert.throws(()=>applyIntent(state,{action,quantity:150},'Publish the work ticket for 150 shirts'),/Review and approve/);
    assert.throws(()=>applyIntent(state,{action,budgetDollars:2000},'Prepare a launch with budget 2000'),/Review and approve/);
  }
  assert.equal(state.rehearsal.approved?.quantity,140);
});

test('a saved packet belongs to its exact approval, even when a later order has the same quantity',()=>{
  let state=applyIntent(newConversation('packets'),{action:'review',quantity:150},'150 shirts').state;state.revision=1;
  state=applyIntent(state,{action:'approve'},'Approve').state;state.revision=2;
  const packet={id:'saved',name:'Approved work packet · 150 shirts',url:'/packet',approvalRevision:state.approvalRevision!,approval:{...state.rehearsal.approved!}};
  assert.equal(isCurrentPacket(state,packet),true);
  assert.equal(isCurrentPacket(state,{id:'legacy',name:packet.name,url:packet.url}),false);
  const noted=applyIntent(state,{action:'remember',memoryNote:'Never split shipments.'},'Never split shipments').state;noted.revision=3;
  state=applyIntent(noted,{action:'review',budgetDollars:2000},'Budget 2000 dollars').state;state.revision=4;
  state=applyIntent(state,{action:'approve'},'Approve').state;
  assert.equal(state.rehearsal.approved?.quantity,150);assert.equal(state.rehearsal.approved?.totalCents,195000);
  assert.equal(isCurrentPacket(state,packet),false);
});

test('company instruction survives a fresh session and changes the next decision',async()=>{
  const dir=await temporary();
  try{
    const store=new CompanyWorkspace(dir);
    const noted=applyIntent(newConversation('first'),{action:'remember',memoryNote:'Never split shipments.'},'Remember never to split shipments').state;
    await store.merge(noted);
    const reopened=await new CompanyWorkspace(dir).read();
    const fresh={...newConversation('second'),notes:reopened.notes};
    const reviewed=applyIntent(fresh,{action:'review',quantity:150},'150 shirts');
    assert.equal(reviewed.state.rehearsal.proposal?.chosen,null);
    const raised=applyIntent(reviewed.state,{action:'review',budgetDollars:2000},'Budget is 2000 dollars');
    assert.equal(raised.state.rehearsal.proposal?.chosen?.id,'express');
    await writeFile(resolve(dir,'memory.json'),'{broken');
    await assert.rejects(store.read());assert.equal(await readFile(resolve(dir,'memory.json'),'utf8'),'{broken');
  }finally{await rm(dir,{recursive:true,force:true});}
});

test('company data drives rates and strict Hotdata results reject partial facts',async()=>{
  const company=validateCompany(JSON.parse(await readFile('fixtures/company.json','utf8')));
  company.stock.available=80;
  assert.equal(sampleProposal(150,200000,company).chosen?.totalCents,181000);
  assert.deepEqual(hotdataRows({columns:['available'],rows:[[80]],row_count:1}),[{available:80}]);
  for(const bad of [{columns:['a'],rows:[[1]],truncated:true},{columns:['a','a'],rows:[[1,2]]},{columns:['a'],rows:[[1]],total_row_count:2},{columns:['a'],rows:[[]]}])assert.throws(()=>hotdataRows(bad));
});

test('another conversation changing policy or source invalidates both approval and draft eligibility',()=>{
  let state=applyIntent(newConversation('first'),{action:'review',quantity:150},'150 shirts').state;
  state.dataRevision='original';state=applyIntent(state,{action:'approve'},'Yes approve').state;
  const changed=refreshCompanyContext(state,'original',['Never split shipments.']);
  assert.equal(changed.rehearsal.approved,null);assert.equal(changed.rehearsal.proposal,null);
  assert.equal(applyIntent(changed,{action:'draft'},'Write the packet').draft,null);
  assert.equal(applyIntent(changed,{action:'approve'},'Yes approve').state.rehearsal.approved,null);
  const pricesChanged=refreshCompanyContext(state,'new-price-file',[]);
  assert.equal(pricesChanged.rehearsal.approved,null);assert.equal(pricesChanged.rehearsal.proposal,null);
  assert.equal(refreshCompanyContext(state,'original',[]).rehearsal.approved?.totalCents,175000);
});

test('the spoken explanation uses the actual company deadline',async()=>{
  const company=validateCompany(JSON.parse(await readFile('fixtures/company.json','utf8')));company.deadline='2026-09-22';
  const result=applyIntent(newConversation('date'),{action:'review',quantity:150},'review',company);
  assert.equal(result.state.rehearsal.proposal?.chosen?.id,'standard');assert.match(result.reply!,/September 22/);assert.doesNotMatch(result.reply!,/September 18/);
});

test('a failed Hotdata create is reconciled and only this run databases are deleted',async()=>{
  const dir=await temporary();
  const company=validateCompany(JSON.parse(await readFile('fixtures/company.json','utf8')));
  try{
    await writeFile(resolve(dir,'hotdata-allowance.json'),JSON.stringify({enabled:true,workspaceId:'worktest',freeCreditConfirmed:true,confirmedAvailableUsd:95,maxInputBytes:25000,validUntil:new Date(Date.now()+60000).toISOString(),maxRuns:1,proof:'isolated transport fault test; no API calls'}));
    const created:{id:string;name:string}[]=[],deleted:string[]=[];
    const fake=async(_workspace:string,method:string,path:string,body?:unknown):Promise<unknown>=>{
      const b=body as {name:string};
      if(method==='POST'&&path==='/v1/databases'){
        const db={id:'db-'+created.length,name:b.name};created.push(db);
        if(b.name.includes('shipping'))throw new Error('Create response lost after server write');return db;
      }
      if(method==='GET')return {databases:[...created,{id:'untouched',name:'Another company database'}],has_more:false};
      if(method==='DELETE'){deleted.push(path.split('/').at(-1)!);return null;}
      return {ok:true};
    };
    await assert.rejects(runDataWorkers(dir,company,[],'source',fake),/Create response lost/);
    assert.deepEqual(deleted.sort(),created.map(d=>d.id).sort());assert.ok(!deleted.includes('untouched'));
    assert.equal(JSON.parse(await readFile(resolve(dir,'hotdata-run-count.json'),'utf8')).used,1);
  }finally{await rm(dir,{recursive:true,force:true});}
});

test('repeating a prior instruction makes it current again after a contrary instruction',async()=>{
  const dir=await temporary();
  try{
    const store=new CompanyWorkspace(dir);let state=newConversation('repeat');
    for(const note of ['Never split shipments.','Allow split shipments.','Never split shipments.']){
      state.notes=(await store.read()).notes;
      state=applyIntent(state,{action:'remember',memoryNote:note},note).state;
      await store.merge(state);
    }
    const fresh={...newConversation('fresh'),notes:(await store.read()).notes};
    assert.equal(fresh.notes.at(-1),'Never split shipments.');
    assert.equal(applyIntent(fresh,{action:'review',quantity:150},'150 shirts').state.rehearsal.proposal?.chosen,null);
  }finally{await rm(dir,{recursive:true,force:true});}
});

test('newer retrieved Cognee memory restores an empty cache and cannot replace a later local revision',async()=>{
  const dir=await temporary();
  try{
    const store=new CompanyWorkspace(dir);
    const retained={schema:1 as const,revision:4,notes:['Never split shipments.'],approvals:[{conversationId:'past-conversation',quantity:150,totalCents:195000,option:'Express',at:new Date().toISOString()}],updatedAt:new Date().toISOString()};
    await store.restoreIfNewer(retained);
    const fresh={...newConversation('recovered'),notes:(await new CompanyWorkspace(dir).read()).notes};
    assert.equal(applyIntent(fresh,{action:'review',quantity:150},'150shirts').state.rehearsal.proposal?.chosen,null);
    await store.restoreIfNewer({...retained,revision:3,notes:['Allow split shipments.']});
    assert.deepEqual((await store.read()).notes,retained.notes);
  }finally{await rm(dir,{recursive:true,force:true});}
});

test('only a contradictory recognized shipment rule can make an instruction historical',()=>{
  const unrelated=['Never split shipments.','The customer asked about split sizes.'];
  assert.equal(shipmentPolicyInstruction(unrelated[1]),null);
  assert.equal(splitForbidden(unrelated),true);
  assert.deepEqual(historicalShipmentPolicyIndexes(unrelated),[]);
  const permitted=[...unrelated,'Allow split shipments.'];
  assert.equal(splitForbidden(permitted),false);
  assert.deepEqual(historicalShipmentPolicyIndexes(permitted),[0]);
  const forbidden=[...permitted,'Do not use split shipments.','Owner approval is required.'];
  assert.equal(splitForbidden(forbidden),true);
  assert.deepEqual(historicalShipmentPolicyIndexes(forbidden),[2]);
  assert.deepEqual(historicalShipmentPolicyIndexes(['Allow split shipments.','Split shipments are okay.']),[]);
});

test('live progress reflects actual pending work and an older run cannot overwrite a newer one',async()=>{
  const id='11111111-1111-4111-8111-111111111111';
  const first=beginProgress(id);let release!:()=>void;
  const task=first.run('hotdata','Query inventory',()=>new Promise<void>(resolve=>{release=resolve;}));
  const pending=progressSnapshot(id)!;assert.equal(pending.active,true);assert.equal(pending.steps[0].status,'running');assert.equal(pending.steps[0].finishedAt,undefined);
  pending.steps[0].task='tampered';assert.equal(progressSnapshot(id)!.steps[0].task,'Query inventory');
  release();await task;assert.equal(progressSnapshot(id)!.steps[0].status,'complete');assert.ok(progressSnapshot(id)!.steps[0].finishedAt);
  const second=beginProgress(id);const fresh=progressSnapshot(id)!;assert.notEqual(fresh.runId,pending.runId);assert.equal(fresh.steps.length,0);
  first.end();assert.equal(progressSnapshot(id)!.active,true);
  second.record('snapshot','hotdata','Reuse verified data','reused');second.end();
  assert.equal(progressSnapshot(id)!.active,false);assert.equal(progressSnapshot(id)!.steps[0].status,'reused');
  assert.equal(progressSnapshot('../private'),null);
});

test('live progress failure never turns unfinished work into success or exposes provider errors',async()=>{
  const id='22222222-2222-4222-8222-222222222222';const progress=beginProgress(id);
  progress.record('incomplete','hotdata','Query shipping','running');
  await assert.rejects(progress.run('rocketride','Verify proposal',async()=>{throw new Error('PRIVATE_PROVIDER_DETAIL');}));
  progress.end();const snapshot=progressSnapshot(id)!;
  assert.equal(snapshot.active,false);assert.equal(snapshot.steps.every(step=>step.status==='error'),true);
  assert.doesNotMatch(JSON.stringify(snapshot),/PRIVATE_PROVIDER_DETAIL/);
});

test('external actions preserve every potential quantity and budget amendment for exact approval checks',()=>{
  for(const action of ['launch','publish'] as const){
    for(const [quantity,word] of [[60,'sixty'],[13,'thirteen'],[90,'ninety']] as const){
      assert.equal(sanitizeIntent({action,quantity},`Publish the work ticket for ${word} shirts.`).quantity,quantity);
    }
    assert.equal(sanitizeIntent({action,budgetDollars:1000},'Publish the work ticket with a price ceiling of 1000.').budgetDollars,1000);
  }
});

// EXPORT-SPECIFIC CHECK — generated by export-judges.py for the exported server surface.
test('exported local server keeps its localhost, origin, CSP and static-file boundaries', async () => {
  const dir = await temporary();
  await writeFile(resolve(dir, 'index.html'), '<!doctype html><title>Redirect</title>');
  await writeFile(resolve(dir, 'talk.html'), '<!doctype html><title>Talk</title>');
  const server = makeServer({ storePath: resolve(dir, 'data/checklist.json'), publicPath: dir, monitor: false });
  await new Promise<void>(resolveListen => server.listen(0, '127.0.0.1', resolveListen));
  const address = server.address() as { port: number };
  const origin = `http://127.0.0.1:${address.port}`;
  try {
    assert.equal((await fetch(origin)).status, 200);
    const talk = await fetch(`${origin}/talk`);
    assert.equal(talk.status, 200);
    assert.match(talk.headers.get('content-security-policy')!, /frame-ancestors 'none'/);
    assert.match(talk.headers.get('content-security-policy')!, /media-src 'self' blob:/);
    assert.equal((await fetch(`${origin}/.env`)).status, 404);
    assert.equal((await fetch(`${origin}/evidence/unknown`)).status, 404);
    assert.equal((await fetch(`${origin}/api/tasks/anything`, { method: 'PATCH', headers: { Origin: origin, 'Content-Type': 'application/json' }, body: '{"revision":0,"edit":{"status":"active"}}' })).status, 404);
    assert.equal((await fetch(`${origin}/api/conversation/new`, { method: 'POST', headers: { Origin: 'https://outside.example', 'Content-Type': 'application/json' }, body: '{}' })).status, 403);
    const badHost = await new Promise<number | undefined>((resolveResponse, reject) => {
      const req = request(origin, { headers: { Host: 'outside.example' } }, res => { res.resume(); resolveResponse(res.statusCode); });
      req.on('error', reject); req.end();
    });
    assert.equal(badHost, 403);
    const company = await fetch(`${origin}/api/company`);
    assert.equal(company.status, 200);
    assert.equal((await company.json()).data.sampleData, true);
  } finally {
    const closed = new Promise<void>((resolveClose, reject) => server.close(error => error ? reject(error) : resolveClose()));
    server.closeAllConnections();
    await closed;
    await rm(dir, { recursive: true, force: true });
  }
});
