import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,readFile} from 'node:fs/promises';import {createPrintfulDraft} from '../src/printful-draft.ts';
const parent=process.env.PRINTFUL_TEST_ROOT||`${process.cwd()}/run/`;
const config=async()=>({recipient:{name:'Example Owner',address1:'1 Example Lane',city:'Example',state_code:'CA',country_code:'US',zip:'90001'}});
const token=async()=> 'test-only-not-a-real-token';
test('Printful creates only one unsubmitted configured sample draft and returns no private data',async()=>{const dir=await mkdtemp(parent+'printful-test-');let posts=0;let body:any;try{const fake=(async(url:any,init:any)=>{assert.doesNotMatch(String(url),/confirm|confirmation/);assert.equal(init.redirect,'error');if(init.method==='POST'){posts++;body=JSON.parse(init.body);assert.ok(body.external_id.length<=32,'Printful external_id maximum is 32 characters');assert.equal(body.order_items.length,1);const item=body.order_items[0];assert.equal(item.catalog_variant_id,4017);assert.equal(item.quantity,1);assert.equal(item.placements[0].placement,'front');assert.equal(item.placements[0].technique,'dtg');assert.equal(item.placements[0].layers[0].type,'file');assert.equal(item.placements[0].layers[0].url,'https://raw.githubusercontent.com/gtrush03/trusynth/master/brand/tru@16x.png');assert.equal('retail_costs' in body,false);return Response.json({data:{id:123}});}return Response.json({data:{id:123,status:'draft',external_id:body.external_id,order_items:body.order_items,recipient:body.recipient}});}) as typeof fetch;const first=await createPrintfulDraft(dir,{fetch:fake,config,token});assert.equal(first.status,'draft');assert.equal(first.printReady,false);assert.equal(first.itemCount,1);assert.doesNotMatch(JSON.stringify(first),/Example Owner|Example Lane|test-only|recipient|90001/);assert.equal((await createPrintfulDraft(dir,{fetch:fake,config,token})).reused,true);assert.equal(posts,1);}finally{await rm(dir,{recursive:true,force:true});}});
test('Ambiguous creation survives restart and cannot POST again or leak provider errors',async()=>{const dir=await mkdtemp(parent+'printful-test-');let posts=0;try{const fake=(async()=>{posts++;throw Error('private-token-and-address');}) as typeof fetch;await assert.rejects(createPrintfulDraft(dir,{fetch:fake,config,token}),e=>e instanceof Error&&!e.message.includes('private-token'));await assert.rejects(createPrintfulDraft(dir,{fetch:fake,config,token}),/no automatic resend/);assert.equal(posts,1);assert.equal(JSON.parse(await readFile(dir+'/printful/attempt.json','utf8')).state,'submitting');}finally{await rm(dir,{recursive:true,force:true});}});
test('Known creation resumes GET after failed readback and rejects non-draft status',async()=>{const dir=await mkdtemp(parent+'printful-test-');let posts=0;let ext='';let fail=true;try{const fake=(async(url:any,init:any)=>{if(init.method==='POST'){posts++;ext=JSON.parse(init.body).external_id;return Response.json({data:{id:124}});}if(fail)throw Error('lost readback');return Response.json({data:{id:124,status:'pending',external_id:ext,order_items:[]}});}) as typeof fetch;await assert.rejects(createPrintfulDraft(dir,{fetch:fake,config,token}));fail=false;await assert.rejects(createPrintfulDraft(dir,{fetch:fake,config,token}),/readback does not match/);assert.equal(posts,1);}finally{await rm(dir,{recursive:true,force:true});}});
test('Concurrent calls cannot duplicate creation',async()=>{const dir=await mkdtemp(parent+'printful-test-');let posts=0;let ext='';try{const fake=(async(url:any,init:any)=>{if(init.method==='POST'){posts++;ext=JSON.parse(init.body).external_id;await new Promise(r=>setTimeout(r,10));return Response.json({data:{id:125}});}return Response.json({data:{id:125,status:'draft',external_id:ext,order_items:[{catalog_variant_id:4017,quantity:1}]}});}) as typeof fetch;await Promise.allSettled([createPrintfulDraft(dir,{fetch:fake,config,token}),createPrintfulDraft(dir,{fetch:fake,config,token})]);assert.equal(posts,1);assert.equal((await createPrintfulDraft(dir,{fetch:fake,config,token})).status,'draft');}finally{await rm(dir,{recursive:true,force:true});}});
test('Wrong provider item cannot produce a successful configured-draft receipt',async()=>{const dir=await mkdtemp(parent+'printful-test-');let ext='';try{const fake=(async(url:any,init:any)=>{if(init.method==='POST'){ext=JSON.parse(init.body).external_id;return Response.json({data:{id:126}});}return Response.json({data:{id:126,status:'draft',external_id:ext,order_items:[{catalog_variant_id:4017,quantity:140}]}});}) as typeof fetch;await assert.rejects(createPrintfulDraft(dir,{fetch:fake,config,token}),/readback does not match/);await assert.rejects(readFile(dir+'/printful/receipt.json','utf8'),{code:'ENOENT'});}finally{await rm(dir,{recursive:true,force:true});}});
