import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,readFile,writeFile,rm} from 'node:fs/promises';
import {TENKI_FIXED as fixed,TENKI_GUEST,tenkiAllowance,readTenkiSupplier,uploadTenkiLaunchKit,type TenkiSession,type TenkiOptions} from '../src/tenki-browser.ts';
import {newConversation,applyIntent} from '../src/conversation-model.ts';import {prepareLaunchKit} from '../src/work-ticket.ts';
const base=process.env.TRU_TEST_RUNS??`${process.cwd()}/run/tenki-tests`;
const company=JSON.parse(await readFile('fixtures/company.json','utf8')),code=await readFile('scripts/tenki-browser-read.mjs');
const now=()=>Date.parse('2026-09-11T21:07:00Z');
async function setup(){await mkdir(base,{recursive:true});const root=await mkdtemp(base+'/guard-');await writeFile(root+'/tenki-browser-allowance.json',JSON.stringify({schema:1,enabled:true,...fixed,maxReads:3,maxUploads:3,sampleOnly:true}));return root;}
function approved(){let s=applyIntent(newConversation('11111111-1111-4111-8111-111111111111'),{action:'review',quantity:140},'140 shirts',company).state;s.revision=1;s=applyIntent(s,{action:'approve'},'Approve',company).state;s.artifacts.push({id:'packet',url:'/packet',name:'Approved work packet',approvalRevision:s.approvalRevision!,approval:{...s.rehearsal.approved!}});return s;}
function fake(root:string){const calls:string[]=[],writes:Record<string,string>={};let closes=0;const s:TenkiSession={id:fixed.sessionId,workspaceId:fixed.workspaceId,metadata:{runId:fixed.runId},state:'RUNNING',cpuCores:2,memoryMb:4096,diskSizeGb:5,timeoutAt:new Date(fixed.sessionExpiresAt),async readFile(path){calls.push('read:'+path);return path===TENKI_GUEST.script?code:path===TENKI_GUEST.kit?Buffer.from(writes[path]??''):Buffer.from('{"captureAt":"2026-09-11T20:57:56Z","lastCaptureAt":"2026-09-11T20:57:56Z"}');},async exec(command,options){calls.push('exec');assert.equal(command,'node');assert.deepEqual(options.args,[TENKI_GUEST.script]);const ledger=JSON.parse(await readFile(root+'/tenki-browser-count.json','utf8'));assert.ok(ledger.reads>0);return {exitCode:0};},async writeFile(path,data){calls.push('write:'+path);const ledger=JSON.parse(await readFile(root+'/tenki-browser-count.json','utf8'));assert.ok(ledger.reads+ledger.uploads>0);writes[path]=data;}};
 const result={outcome:'read',closed:true,url:'https://www.printful.com/custom/mens/t-shirts',httpStatus:200,browserVersion:'140.0.7339.16',title:'Injected catalog',headings:['T-shirts'],textExcerpt:'Injected public text',screenshotBase64:Buffer.from('89504e470d0a1a0a0000','hex').toString('base64'),ms:5,finishedAt:'2026-09-11T21:07:01Z'};
 const options:TenkiOptions={now,connect:async()=>({get:async id=>{calls.push('get');assert.equal(id,fixed.sessionId);return s;},close:()=>{closes++;},stdoutText:()=>JSON.stringify(result)})};return {s,options,calls,writes,result,closed:()=>closes};}
test('Tenki absent/disabled makes no provider call; invalid enabled config fails closed',async()=>{const root=await setup();try{const f=fake(root);await rm(root+'/tenki-browser-allowance.json');assert.equal(await readTenkiSupplier(root,f.options),null);assert.equal(f.calls.length,0);await writeFile(root+'/tenki-browser-allowance.json','{"enabled":false}');assert.equal(await tenkiAllowance(root,now()),null);await writeFile(root+'/tenki-browser-allowance.json','{"enabled":true}');await assert.rejects(readTenkiSupplier(root,f.options),/allowance/);assert.equal(f.calls.length,0);}finally{await rm(root,{recursive:true,force:true});}});
test('Tenki exact session, workspace, run, resources and expiry checked before execution',async()=>{for(const field of ['id','workspaceId','metadata','cpuCores','memoryMb','diskSizeGb','timeoutAt']){const root=await setup();try{const f=fake(root);(f.s as any)[field]=field==='metadata'?{runId:'wrong'}:field==='timeoutAt'?new Date('2027-01-01'):field.endsWith('Id')||field==='id'?'wrong':99;await assert.rejects(readTenkiSupplier(root,f.options),/identity/);assert.equal(f.calls.includes('exec'),false);assert.equal(f.closed(),1);}finally{await rm(root,{recursive:true,force:true});}}const root=await setup();try{const f=fake(root);await assert.rejects(readTenkiSupplier(root,{...f.options,now:()=>Date.parse(fixed.validUntil)}),/expired/);assert.equal(f.calls.length,0);}finally{await rm(root,{recursive:true,force:true});}});
test('Tenki read maps actual result and PNG; fourth additional read never executes',async()=>{const root=await setup();try{const f=fake(root);for(let i=0;i<3;i++){const r=await readTenkiSupplier(root,f.options);assert.equal(r?.browser.cdpHost,'Tenki Cloud');assert.equal(r?.browser.version,f.result.browserVersion);assert.equal(r?.tab.closed,true);assert.ok(r?.screenshot?.path.startsWith(root+'/browser-shots/'));}await assert.rejects(readTenkiSupplier(root,f.options),/exhausted/);assert.equal(f.calls.filter(x=>x==='exec').length,3);assert.equal(f.closed(),3);}finally{await rm(root,{recursive:true,force:true});}});
test('Tenki unsafe result or changed guest script never claims success; attempt remains spent',async()=>{const root=await setup();try{const f=fake(root);f.result.url='https://evil.invalid';await assert.rejects(readTenkiSupplier(root,f.options),/not verified/);assert.equal(Object.keys(f.writes).length,0);f.s.readFile=async()=>Buffer.from('changed');await assert.rejects(readTenkiSupplier(root,f.options),/script changed/);assert.equal(f.calls.filter(x=>x==='exec').length,1);assert.equal(JSON.parse(await readFile(root+'/tenki-browser-count.json','utf8')).reads,2);}finally{await rm(root,{recursive:true,force:true});}});
test('Tenki exact approved kit uploads to fixed files and preserves capture time; repeat reuses receipt',async()=>{const root=await setup();try{const f=fake(root),s=approved(),kit=prepareLaunchKit(s,company);const r=await uploadTenkiLaunchKit(root,s,company,kit,f.options);assert.equal(r?.url,fixed.previewUrl);assert.equal(f.writes[TENKI_GUEST.kit],kit.markdown);const st=JSON.parse(f.writes[TENKI_GUEST.status]);assert.equal(st.captureAt,'2026-09-11T20:57:56Z');assert.equal(st.quantity,140);assert.equal(st.approvalFingerprint,kit.fingerprint);assert.equal((await uploadTenkiLaunchKit(root,s,company,kit,f.options))?.reused,true);assert.equal(f.calls.filter(x=>x.startsWith('write:')).length,2);}finally{await rm(root,{recursive:true,force:true});}});
test('Tenki upload rejects changed quantity, budget, revision, content or stale cloud fingerprint without writes',async()=>{for(const mutate of [(s:any,k:any)=>s.quantity++, (s:any,k:any)=>s.budgetCents++, (s:any,k:any)=>s.approvalRevision++, (s:any,k:any)=>k.markdown+='extra', (s:any,k:any)=>s.cloudReview={fingerprint:'stale',receiptId:'x'}]){const root=await setup();try{const f=fake(root),s=approved(),kit=prepareLaunchKit(s,company);mutate(s,kit);await assert.rejects(uploadTenkiLaunchKit(root,s,company,kit,f.options));assert.equal(f.calls.length,0);}finally{await rm(root,{recursive:true,force:true});}}});
test('Tenki uncertain upload is counted and blocked from duplicate, concurrent call cannot reserve',async()=>{const root=await setup();try{const f=fake(root),s=approved(),kit=prepareLaunchKit(s,company);f.s.writeFile=async()=>{throw Error('injected uncertain write');};await assert.rejects(uploadTenkiLaunchKit(root,s,company,kit,f.options),/not confirmed/);const calls=f.calls.length;await assert.rejects(uploadTenkiLaunchKit(root,s,company,kit,f.options),/unconfirmed/);assert.equal(f.calls.length,calls);assert.equal(JSON.parse(await readFile(root+'/tenki-browser-count.json','utf8')).uploads,1);await writeFile(root+'/tenki-browser.lock','held');await assert.rejects(readTenkiSupplier(root,f.options),/active or unconfirmed/);}finally{await rm(root,{recursive:true,force:true});}});
test('Tenki total timeout spends one attempt, closes host client, makes no later writes',async()=>{const root=await setup();try{const f=fake(root);f.s.exec=async()=>new Promise(()=>{});await assert.rejects(readTenkiSupplier(root,{...f.options,timeoutMs:15}),/timed out/);assert.equal(f.closed(),1);assert.equal(Object.keys(f.writes).length,0);assert.equal(JSON.parse(await readFile(root+'/tenki-browser-count.json','utf8')).reads,1);}finally{await rm(root,{recursive:true,force:true});}});
