import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,readFile,writeFile,rm} from 'node:fs/promises';
import {prepareLaunchKit,publishWorkTicket,TICKET_REPO} from '../src/work-ticket.ts';
import {newConversation,applyIntent} from '../src/conversation-model.ts';
const base=process.env.TRU_TEST_RUNS??`${process.cwd()}/run/test-runs`;
const company=JSON.parse(await readFile('fixtures/company.json','utf8'));
function approved(){let s=applyIntent(newConversation('11111111-1111-4111-8111-111111111111'),{action:'review',quantity:140},'140 shirts',company).state;s.revision=1;s=applyIntent(s,{action:'approve'},'Approve',company).state;s.artifacts.push({id:'packet',url:'/packet',name:'Approved work packet',approvalRevision:s.approvalRevision!,approval:{...s.rehearsal.approved!}});return s;}
async function setup(){await mkdir(base,{recursive:true});const root=await mkdtemp(base+'/ticket-');await writeFile(root+'/work-ticket-allowance.json',JSON.stringify({enabled:true,repo:TICKET_REPO,sampleOnly:true,maxIssues:3,validUntil:new Date(Date.now()+60000).toISOString()}));return root;}
test('handoff needs the current approved packet and accepts no private company data',()=>{assert.throws(()=>prepareLaunchKit(newConversation('new'),company),/Approve/);const s=approved();const kit=prepareLaunchKit(s,company);assert.equal(kit.quantity,140);assert.match(kit.email.body,/not a supplier quote or a purchase order/);assert.match(kit.markdown,/unpublished/);assert.throws(()=>prepareLaunchKit(s,{...company,sampleData:false}),/sample/);s.approvalRevision=99;assert.throws(()=>prepareLaunchKit(s,company),/Approve/);});
test('published ticket is constrained to the owned project and retries reuse its receipt',async()=>{const root=await setup(),kit=prepareLaunchKit(approved(),company),calls:string[][]=[];try{const fake=async(args:string[])=>{calls.push(args);if(args[0]==='api')return 'gtrush03';if(args[1]==='list')return '[]';if(args[1]==='create'){const body=await readFile(args.at(-1)!,'utf8');assert.equal(body,kit.markdown);assert.equal(args[3],TICKET_REPO);return 'https://github.com/gtrush03/synth-order-desk/issues/1\n';}throw Error('Unexpected command');};const first=await publishWorkTicket(root,kit,fake);assert.equal(first.number,1);assert.equal(first.reused,false);const second=await publishWorkTicket(root,kit,fake);assert.equal(second.reused,true);assert.equal(calls.filter(a=>a[1]==='create').length,1);}finally{await rm(root,{recursive:true,force:true});}});
test('uncertain publication stops before a duplicate and remote identity mismatch cannot post',async()=>{const root=await setup(),kit=prepareLaunchKit(approved(),company);let creates=0;try{const fake=async(args:string[])=>{if(args[0]==='api')return 'gtrush03';if(args[1]==='list')return '[]';creates++;throw Error('Connection lost after possible create');};await assert.rejects(publishWorkTicket(root,kit,fake),/Connection lost/);await assert.rejects(publishWorkTicket(root,kit,fake),/previous publication needs verification/);assert.equal(creates,1);await rm(root+'/work-tickets',{recursive:true,force:true});await assert.rejects(publishWorkTicket(root,kit,async()=> 'someone-else'),/expected project owner/);}finally{await rm(root,{recursive:true,force:true});}});
