// EXPORT BUILD SCRIPT — generated by export-judges.py. Builds only the talking order desk.
import { mkdir, copyFile, access } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { resolve } from 'node:path';
const project = resolve(import.meta.dirname, '..');
const output = process.env.TRU_PLAN_OUTPUT ?? resolve(project, 'run');
await mkdir(resolve(output, 'public'), { recursive: true });
await mkdir(resolve(output, 'dist'), { recursive: true });
await mkdir(resolve(output, 'bin'), { recursive: true });
await mkdir(resolve(output, 'conversation/company'), { recursive: true });
try { await access(resolve(output, 'conversation/company/data.json')); } catch { await copyFile(resolve(project, 'fixtures/company.json'), resolve(output, 'conversation/company/data.json')); }
if (process.env.TRU_SKIP_NATIVE === '1') {
  console.log('Skipping the Apple on-device model helper (TRU_SKIP_NATIVE=1). Conversation turns will report that the local model needs to be built.');
} else {
  const native = spawnSync('xcrun', ['swiftc', '-parse-as-library', '-module-cache-path', resolve(output, 'swift-cache'), 'native/LocalSynth.swift', '-o', resolve(output, 'bin/synth-local-model')], { cwd: project, stdio: 'inherit' });
  if (native.status !== 0) { console.error('The Swift helper did not compile. This needs macOS 26 with Xcode 26 command-line tools and the FoundationModels framework. Set TRU_SKIP_NATIVE=1 to build without it.'); process.exit(native.status ?? 1); }
}
for (const [input, target, outfile] of [['src/talk.ts', 'browser', 'public/talk.js'], ['src/main.ts', 'node', 'dist/server.js']]) {
  const result = spawnSync('bun', ['build', input, `--target=${target}`, `--outfile=${resolve(output, outfile)}`, '--minify'], { cwd: project, stdio: 'inherit' });
  if (result.status !== 0) process.exit(result.status ?? 1);
}
for (const name of ['index.html', 'talk.html', 'talk.css', 'favicon.svg', 'wordmark.png']) await copyFile(resolve(project, 'public', name), resolve(output, 'public', name));
try { const { readdir } = await import('node:fs/promises'); const logos = await readdir(resolve(project, 'public/sponsors')); await mkdir(resolve(output, 'public/sponsors'), { recursive: true }); for (const name of logos) if (/^[a-z0-9-]+\.(svg|png)$/.test(name)) await copyFile(resolve(project, 'public/sponsors', name), resolve(output, 'public/sponsors', name)); } catch { /* no sponsor marks shipped */ }
console.log(`Built: ${output}`);
