// EXPORT TEST RUNNER — generated by export-judges.py.
import { spawnSync } from 'node:child_process';
import { mkdir, copyFile, access } from 'node:fs/promises';
import { resolve } from 'node:path';
const project = resolve(import.meta.dirname, '..');
const output = process.env.TRU_PLAN_OUTPUT ?? resolve(project, 'run');
await mkdir(resolve(output, 'dist'), { recursive: true });
await mkdir(resolve(output, 'conversation/company'), { recursive: true });
try { await access(resolve(output, 'conversation/company/data.json')); } catch { await copyFile(resolve(project, 'fixtures/company.json'), resolve(output, 'conversation/company/data.json')); }
const paths = [];
const suites = ['order-desk', 'browser-actions', 'work-ticket', 'workspace-map', 'gmail-draft'];
for (const name of ['tenki-browser', 'gpt-live', 'project-email', 'printful-draft']) { try { await access(resolve(project, `tests/${name}.test.ts`)); suites.push(name); } catch { /* optional adapter not included */ } }
for (const name of suites) {
  const path = resolve(output, `dist/${name}.test.js`); paths.push(path);
  const build = spawnSync('bun', ['build', `tests/${name}.test.ts`, '--target=node', `--outfile=${path}`], { cwd: project, stdio: 'inherit' });
  if (build.status !== 0) process.exit(build.status ?? 1);
}
const tests = spawnSync('node', ['--test', ...paths], { cwd: project, stdio: 'inherit', env: { ...process.env, TRU_PLAN_OUTPUT: output, TRU_SOURCE: project } });
process.exit(tests.status ?? 1);
