import {test,expect} from 'bun:test';
import {validateSignup,CONSENT_VERSION,RESOURCE_EMAIL,sha256,readJson} from '../src/domain';
import {signup,people,withdraw,sendReviewedResource,cleanup} from '../src/store';
import worker from '../src/worker';
import {testDatabase} from './sqlite';
const NOW=Date.parse('2026-09-11T20:00:00Z');
const input=(n=0,extra={})=>({name:`Test visitor ${n}`,email:`test${n}@example.com`,role:'Boundary test fixture',interest:'Security',storageConsent:true,directoryConsent:false,followupConsent:false,consentVersion:CONSENT_VERSION,...extra});
test('invalid input, unchecked/string consent, stale terms and injected header are rejected',()=>{for(const patch of [{email:'a\r\nBcc:x@y.com'},{email:'bad'},{name:'<script>'},{storageConsent:false},{storageConsent:'true'},{directoryConsent:'true'},{followupConsent:1},{consentVersion:'old'},{interest:'invented'},{website:'bot.example'},{role:'x'.repeat(101)}])expect(()=>validateSignup(input(0,patch))).toThrow();expect(validateSignup(input())).toMatchObject({email:'test0@example.com',directoryConsent:false});});
test('body cap checks real streamed bytes, including absent or dishonest content length',async()=>{for(const content of ['{bad',' '.repeat(4097)])await expect(readJson(new Request('https://event.example/api/signup',{method:'POST',headers:{'content-type':'application/json'},body:content}))).rejects.toThrow();});
test('real SQLite insert persists consent and public projection never exposes private fields',async()=>{const {db,sqlite}=testDatabase();await signup(db,input(0),'ip',NOW);await signup(db,input(1,{directoryConsent:true}),'ip',NOW);const publicData=await people(db,NOW);expect(publicData.people).toHaveLength(1);expect(Object.keys(publicData.people[0])).toEqual(['id','name','role','interest']);expect(JSON.stringify(publicData)).not.toContain('@');expect(sqlite.query('SELECT consent_version FROM visitors').get()).toEqual({consent_version:CONSENT_VERSION});});
test('five per IP/hour succeeds; sixth refuses; later hour resets; duplicate cannot overwrite consent',async()=>{const {db}=testDatabase();for(let i=0;i<5;i++)await signup(db,input(i),'same',NOW);await expect(signup(db,input(5),'same',NOW)).rejects.toThrow('limit');await expect(signup(db,input(0,{directoryConsent:true}),'different',NOW)).rejects.toThrow();await signup(db,input(6),'same',NOW+3600001);expect((await people(db,NOW)).people).toHaveLength(0);});
test('global 200 signups/day boundary and 500 total storage boundary are atomic SQL conditions',async()=>{const {db,sqlite}=testDatabase();for(let i=0;i<200;i++)await signup(db,input(i),`ip${i}`,NOW);await expect(signup(db,input(200),'newip',NOW)).rejects.toThrow();for(let i=200;i<400;i++)await signup(db,input(i),`ip${i}`,NOW+86400001);for(let i=400;i<500;i++)await signup(db,input(i),`ip${i}`,NOW+2*86400001);await expect(signup(db,input(500),'new',NOW+3*86400001)).rejects.toThrow();expect(sqlite.query('SELECT COUNT(*) n FROM visitors').get()).toEqual({n:500});});
test('removal requires private token, redacts PII, disables directory and follow-up, cleanup purges',async()=>{const {db,sqlite}=testDatabase();const r=await signup(db,input(0,{directoryConsent:true,followupConsent:true}),'ip',NOW);await expect(withdraw(db,r.id,'wrong',NOW)).rejects.toThrow();await withdraw(db,r.id,r.manageToken,NOW);expect((await people(db,NOW)).people).toEqual([]);expect(sqlite.query('SELECT followup_consent,email FROM visitors').get()).toEqual({followup_consent:0,email:`removed-${r.id}@invalid.example`});await cleanup(db,NOW);expect(sqlite.query('SELECT COUNT(*) n FROM visitors').get()).toEqual({n:0});});
test('expired visitors cannot appear, send, or survive daily retention cleanup',async()=>{const {db,sqlite}=testDatabase();const r=await signup(db,input(0,{directoryConsent:true,followupConsent:true}),'ip',NOW);const later=NOW+30*86400000;expect((await people(db,later)).people).toEqual([]);await expect(sendReviewedResource(db,async()=>({accepted:true,providerId:'TEST'}),{visitorId:r.id,reviewedByRoot:true,approvedPreviewHash:'x'},later)).rejects.toThrow('consent');await cleanup(db,later);expect(sqlite.query('SELECT COUNT(*) n FROM visitors').get()).toEqual({n:0});});
test('sender held, no consent, mismatched review and no ROOT approval never invoke sender',async()=>{const {db}=testDatabase();const r=await signup(db,input(),'ip',NOW);let calls=0;const fake=async()=>{calls++;return {accepted:true as const,providerId:'TEST ONLY'};};await expect(sendReviewedResource(db,undefined,{visitorId:r.id,reviewedByRoot:true,approvedPreviewHash:'x'},NOW)).rejects.toThrow('held');await expect(sendReviewedResource(db,fake,{visitorId:r.id,reviewedByRoot:true,approvedPreviewHash:'x'},NOW)).rejects.toThrow('consent');const yes=await signup(db,input(1,{followupConsent:true}),'ip',NOW);await expect(sendReviewedResource(db,fake,{visitorId:yes.id,reviewedByRoot:false,approvedPreviewHash:'x'},NOW)).rejects.toThrow('ROOT');await expect(sendReviewedResource(db,fake,{visitorId:yes.id,reviewedByRoot:true,approvedPreviewHash:'x'},NOW)).rejects.toThrow('differs');expect(calls).toBe(0);});
test('ten reviewed sends/day cap persists; idempotency prevents repeat; accepted is never delivered',async()=>{const {db}=testDatabase();let calls=0;const fake=async()=>({accepted:true as const,providerId:`TEST-${++calls}`});for(let i=0;i<11;i++){const r=await signup(db,input(i,{followupConsent:true}),`ip${i}`,NOW);const approvedPreviewHash=await sha256(JSON.stringify({...RESOURCE_EMAIL,to:input(i).email}));const review={visitorId:r.id,approvedPreviewHash,reviewedByRoot:true};if(i<10){expect(await sendReviewedResource(db,fake,review,NOW)).toMatchObject({status:'accepted',delivered:false});await expect(sendReviewedResource(db,fake,review,NOW)).rejects.toThrow();}else await expect(sendReviewedResource(db,fake,review,NOW)).rejects.toThrow('Daily limit');}expect(calls).toBe(10);});
test('ambiguous provider failure retains reservation and blocks retries',async()=>{const {db,sqlite}=testDatabase();const r=await signup(db,input(0,{followupConsent:true}),'ip',NOW);const approvedPreviewHash=await sha256(JSON.stringify({...RESOURCE_EMAIL,to:input().email}));let calls=0;const fake=async()=>{calls++;throw new Error('private provider detail');};const review={visitorId:r.id,approvedPreviewHash,reviewedByRoot:true};await expect(sendReviewedResource(db,fake,review,NOW)).rejects.toThrow('unconfirmed');await expect(sendReviewedResource(db,fake,review,NOW)).rejects.toThrow('prior attempt');expect(calls).toBe(1);expect(sqlite.query('SELECT status FROM mail_attempts').get()).toEqual({status:'uncertain'});});
test('Worker boundary: held signup, cross-origin rejection, actual local persistence, no public send endpoint',async()=>{const {db}=testDatabase();const env={EVENT_DB:db,SIGNUPS_ENABLED:'true',DEPLOYMENT_LABEL:'TEST',ASSETS:{fetch:()=>new Response('asset')}} as unknown as Env;const req=(path='/api/signup',origin='https://event.example')=>new Request(`https://event.example${path}`,{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(input())});expect((await worker.fetch(req('/api/signup','https://evil.example'),env)).status).toBe(403);expect((await worker.fetch(req(),{...env,SIGNUPS_ENABLED:'false'})).status).toBe(503);expect((await worker.fetch(req(),env)).status).toBe(201);expect((await worker.fetch(req('/api/send'),env)).status).toBe(404);const status=await (await worker.fetch(new Request('https://event.example/api/status'),env)).json();expect(status).toMatchObject({mail:'held',signup:'ready'});});

test('IP rate limit remains effective across midnight',async()=>{const {db}=testDatabase();const midnight=Date.parse('2026-09-12T00:00:00Z');for(let i=0;i<5;i++)await signup(db,input(i),'same',midnight-1000);await expect(signup(db,input(5),'same',midnight+1000)).rejects.toThrow('limit');});

test('scheduled Worker invokes actual expired-record purge',async()=>{const {db,sqlite}=testDatabase();await signup(db,input(),'ip',Date.now()-31*86400000);await worker.scheduled({} as ScheduledController,{EVENT_DB:db} as Env);expect(sqlite.query('SELECT COUNT(*) n FROM visitors').get()).toEqual({n:0});});

test('automatic followup requires operator enable, exact content hash and binding; never accepts request control',async()=>{
 const {requestedFollowup}=await import('../src/followup');const {db}=testDatabase();const now=Date.now();const r=await signup(db,input(77,{followupConsent:true}),'ip',now);let calls=0;const service={fetch:async()=>{calls++;return Response.json({accepted:true,providerId:'FAKE-SERVICE'});}} as unknown as Fetcher;
 const contentHash=await sha256(JSON.stringify(RESOURCE_EMAIL));
 for(const env of [{},{RESOURCE_MAIL_ENABLED:'true',RESOURCE_APPROVED_HASH:contentHash},{RESOURCE_MAIL_ENABLED:'false',RESOURCE_APPROVED_HASH:contentHash,SYNTH_SENDER:service},{RESOURCE_MAIL_ENABLED:'true',RESOURCE_APPROVED_HASH:'wrong',SYNTH_SENDER:service}])expect((await requestedFollowup(db,env,r.id)).emailStatus).toBe('held');
 expect(calls).toBe(0);expect((await requestedFollowup(db,{RESOURCE_MAIL_ENABLED:'true',RESOURCE_APPROVED_HASH:contentHash,SYNTH_SENDER:service},r.id)).emailStatus).toBe('accepted');expect(calls).toBe(1);
 await requestedFollowup(db,{RESOURCE_MAIL_ENABLED:'true',RESOURCE_APPROVED_HASH:contentHash,SYNTH_SENDER:service},r.id);expect(calls).toBe(1);
 const no=await signup(db,input(78),'other',now);expect((await requestedFollowup(db,{RESOURCE_MAIL_ENABLED:'true',RESOURCE_APPROVED_HASH:contentHash,SYNTH_SENDER:service},no.id)).emailStatus).toBe('not-requested');expect(calls).toBe(1);
});

test('signup route triggers only explicitly requested fixed content; client cannot override sender or text',async()=>{
 const {db}=testDatabase();let captured:Record<string,unknown>|undefined;let calls=0;const service={fetch:async(req:Request)=>{calls++;captured=await req.json() as Record<string,unknown>;return Response.json({accepted:true,providerId:'TEST-AUTO'});}};
 const env={EVENT_DB:db,SIGNUPS_ENABLED:'true',RESOURCE_MAIL_ENABLED:'true',RESOURCE_APPROVED_HASH:await sha256(JSON.stringify(RESOURCE_EMAIL)),SYNTH_SENDER:service,DEPLOYMENT_LABEL:'TEST',ASSETS:{fetch:async()=>new Response('asset')}};
 const request=(data:unknown)=>new Request('https://event.example/api/signup',{method:'POST',headers:{origin:'https://event.example','content-type':'application/json'},body:JSON.stringify(data)});
 const no=await worker.fetch(request(input(81)),env as unknown as Env);expect(no.status).toBe(201);expect(calls).toBe(0);
 const yes=await worker.fetch(request(input(82,{followupConsent:true,text:'ATTACKER BODY',from:'attacker@example.com',RESOURCE_MAIL_ENABLED:'true'})),env as unknown as Env);expect(yes.status).toBe(201);expect(await yes.json()).toMatchObject({emailStatus:'accepted'});expect(calls).toBe(1);expect(captured).toMatchObject({from:RESOURCE_EMAIL.from,to:'test82@example.com',text:RESOURCE_EMAIL.text,subject:RESOURCE_EMAIL.subject});
});

test('actual selftest acceptance migration consumes one Sep11 slot and remains idempotent',async()=>{
 const {readFileSync}=await import('node:fs');const {db,sqlite}=testDatabase();const sql=readFileSync(new URL('../migrations/0002_selftest_receipt.sql',import.meta.url),'utf8');sqlite.exec(sql);sqlite.exec(sql);expect(sqlite.query('SELECT COUNT(*) n FROM mail_attempts').get()).toEqual({n:1});let calls=0;
 for(let i=0;i<10;i++){const r=await signup(db,input(90+i,{followupConsent:true}),`ip${i}`,NOW);const review={visitorId:r.id,reviewedByRoot:true,approvedPreviewHash:await sha256(JSON.stringify({...RESOURCE_EMAIL,to:input(90+i).email}))};const fake=async()=>({accepted:true as const,providerId:`TEST-${++calls}`});if(i<9)await sendReviewedResource(db,fake,review,NOW);else await expect(sendReviewedResource(db,fake,review,NOW)).rejects.toThrow('Daily limit');}expect(calls).toBe(9);
});
