// EXPORT STUB — generated by export-judges.py. The source server exposes /api/fleet for a private
// multi-agent operator monitor that reads fleet state on the source machine. It is not part of the submission;
// this stub keeps the import and returns an empty snapshot.
export async function fleetSnapshot(): Promise<{ generatedAt: string | null; lanes: never[] }> { return { generatedAt: null, lanes: [] }; }
