// EXPORT STUB — generated by export-judges.py. The original src/model.ts also carries the private
// TRU Synth platform task list and roadmap, which are not part of this submission. Only the shared
// types and the constants the server needs are kept. The conversation path does not use TASKS.
export type Status = 'todo' | 'active' | 'blocked' | 'done';
export type Track = 'demo' | 'platform' | 'release';
export type EvidenceKind = 'plan' | 'source' | 'local' | 'live' | 'reported';
export interface Task {
  id: string; title: string; track: Track; phase: string; status: Status;
  priority: 'P0' | 'P1' | 'P2'; owner: string; action: string;
  acceptance: string; depends: string[]; evidence: EvidenceKind;
  proof: string; doc: string; updatedAt?: string; notes?: string; manual?: boolean;
}
export interface TaskEdit { status?: Status; owner?: string; notes?: string }
export interface Change { at: string; taskId: string; fields: string[]; status: Status }
export interface SavedState {
  schema: 1; revision: number;
  edits: Record<string, TaskEdit & { updatedAt: string }>;
  history: Change[];
}
export interface Health {
  id: string; name: string; url: string; status: 'up' | 'degraded' | 'down' | 'unknown';
  code?: number; ms?: number; checkedAt: string | null; detail: string;
}
export interface Source { id: string; title: string; updatedAt: string | null; available: boolean }
export interface Run {
  id: string; started: number; ended: number; events: number; ms: number;
  errors: number; costUsd: number; standIn: boolean; stages: string[];
}
export interface Snapshot {
  revision: number; tasks: Task[]; history: Change[]; health: Health[];
  sources: Source[]; runs: Run[]; generatedAt: string; seedDate: string;
  receipt: { available: boolean; checks: number; passed: number; deployed: boolean; at: string | null };
  machine: { freeGiB: number | null; forge: boolean }; sourceWarnings: string[];
  workers?: { generatedAt: string | null; lanes: WorkerLane[] };
}
export interface WorkerLane {
  id: string; title: string; kind: string; status: string; processAlive: boolean;
  sessionId: string | null; activityAt: string | null; updatedAt: string | null;
  requestedTier: string | null; summary: string; next: string; requests: string[];
  evidence: string[]; owns: string[];
}
export const TRACKS: Record<Track, string> = { demo: 'Hackathon demo', platform: 'Working platform', release: 'Reliable release' };
export const STATUSES: Record<Status, string> = { todo: 'To do', active: 'In progress', blocked: 'Blocked', done: 'Done' };
export const SEED_DATE = '2026-09-11T07:05:00.000Z';
export const DEADLINE = '2026-09-11T15:30:00-07:00';
export const TASKS: Task[] = [];
export const SPONSORS: { id: string; name: string }[] = [];
export const SOURCE_LINKS: { id: string; title: string }[] = [];
