// EXPORT STUB — generated by export-judges.py. The original src/sources.ts pointed the /evidence
// routes and health probes at private documents, receipts and production hosts. This stub keeps the
// same exports, serves only the sanitized evidence and docs shipped in this package, and probes only
// the two local services the app depends on. redact() and summarizeTelemetry() keep their original behaviour.
import { readFile, stat, statfs } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { Health, Run, Source, Snapshot } from './model.ts';
import { readWorkers } from './workers.ts';

const BASE = process.env.TRU_SOURCE ?? process.cwd();
export const DOCUMENTS: Record<string, { title: string; path: string }> = {
  "build-plan": { title: "Receipt build-plan.json", path: resolve(BASE, "evidence/build-plan.json") },
  "full-flow-verification": { title: "Receipt full-flow-verification.json", path: resolve(BASE, "evidence/full-flow-verification.json") },
  "talk-verification": { title: "Receipt talk-verification.json", path: resolve(BASE, "evidence/talk-verification.json") },
  "hotdata-order-proof": { title: "Receipt hotdata-order-proof.json", path: resolve(BASE, "evidence/hotdata-order-proof.json") },
  "hotdata-cleanup-reconciliation": { title: "Receipt hotdata-cleanup-reconciliation.json", path: resolve(BASE, "evidence/hotdata-cleanup-reconciliation.json") },
  "integrated-review": { title: "Receipt integrated-review.json", path: resolve(BASE, "evidence/integrated-review.json") },
  "rote-plays-proof": { title: "Receipt rote-plays-proof.json", path: resolve(BASE, "evidence/rote-plays-proof.json") },
  "hotdata-credits": { title: "Receipt hotdata-credits.json", path: resolve(BASE, "evidence/hotdata-credits.json") },
  "rocketride-staging-credits": { title: "Receipt rocketride-staging-credits.json", path: resolve(BASE, "evidence/rocketride-staging-credits.json") },
  "cognee-cache-recovery": { title: "Receipt cognee-cache-recovery.json", path: resolve(BASE, "evidence/cognee-cache-recovery.json") },
  "submission-category": { title: "Receipt submission-category.json", path: resolve(BASE, "evidence/submission-category.json") },
  "physical-voice-check": { title: "Receipt physical-voice-check.json", path: resolve(BASE, "evidence/physical-voice-check.json") },
  "dataset-source": { title: "Receipt dataset-source.json", path: resolve(BASE, "evidence/dataset-source.json") },
  "launch-intent-check": { title: "Receipt launch-intent-check.json", path: resolve(BASE, "evidence/launch-intent-check.json") },
  "integrated-cloud-flow": { title: "Receipt integrated-cloud-flow.json", path: resolve(BASE, "evidence/integrated-cloud-flow.json") },
  "integration-checks": { title: "Receipt integration-checks.json", path: resolve(BASE, "evidence/integration-checks.json") },
  "failure-cleanup-check": { title: "Receipt failure-cleanup-check.json", path: resolve(BASE, "evidence/failure-cleanup-check.json") },
  "sponsor-logo-sources": { title: "Receipt sponsor-logo-sources.json", path: resolve(BASE, "evidence/sponsor-logo-sources.json") },
  "expanded-intent-check": { title: "Receipt expanded-intent-check.json", path: resolve(BASE, "evidence/expanded-intent-check.json") },
  "rocketride-cloud-ledger": { title: "Receipt rocketride-cloud-ledger.json", path: resolve(BASE, "evidence/rocketride-cloud-ledger.json") },
  "rocketride-cloud-profile": { title: "Receipt rocketride-cloud-profile.json", path: resolve(BASE, "evidence/rocketride-cloud-profile.json") },
  "rocketride-cloud-proof": { title: "Receipt rocketride-cloud-proof.json", path: resolve(BASE, "evidence/rocketride-cloud-proof.json") },
  "rocketride-cloud-receipt-f8c41f59-6ecb-44bb-8d12-354730a4671b": { title: "Receipt rocketride-cloud-receipt-f8c41f59-6ecb-44bb-8d12-354730a4671b.json", path: resolve(BASE, "evidence/rocketride-cloud-receipt-f8c41f59-6ecb-44bb-8d12-354730a4671b.json") },
  "rocketride-cloud-services": { title: "Receipt rocketride-cloud-services.json", path: resolve(BASE, "evidence/rocketride-cloud-services.json") },
  "security-code-enable": { title: "Receipt security-code-enable.json", path: resolve(BASE, "evidence/security-code-enable.json") },
  "security-code-findings": { title: "Receipt security-code-findings.json", path: resolve(BASE, "evidence/security-code-findings.json") },
  "security-code-scope": { title: "Receipt security-code-scope.json", path: resolve(BASE, "evidence/security-code-scope.json") },
  "security-code-triage": { title: "Receipt security-code-triage.json", path: resolve(BASE, "evidence/security-code-triage.json") },
  "full-walkthrough": { title: "Complete talking Synth walkthrough", path: resolve(BASE, "docs/FULL-WALKTHROUGH.md") },
  "sponsor-proof": { title: "Sponsor proof", path: resolve(BASE, "docs/SPONSOR-PROOF.md") },
  "security": { title: "Security and cost limits", path: resolve(BASE, "docs/SECURITY.md") },
  "submission": { title: "Submission text", path: resolve(BASE, "docs/SUBMISSION.md") },
  "readme": { title: "Judge README", path: resolve(BASE, "README.md") },
  "full-flow": { title: "Full conversation and persistent sponsor memory acceptance", path: resolve(BASE, "evidence/full-flow-verification.json") },
  "hotdata-cleanup": { title: "Scoped Hotdata cleanup reconciliation", path: resolve(BASE, "evidence/hotdata-cleanup-reconciliation.json") },
  "judges-repo": { title: "Judge README", path: resolve(BASE, "README.md") }
};

export function redact(text: string): string {
  return text
    .replace(/\b(?:sk-[A-Za-z0-9_-]{12,}|gh[pousr]_[A-Za-z0-9_]{15,})\b/g, '[redacted]')
    .replace(/(Bearer\s+)[A-Za-z0-9._~-]{16,}/gi, '$1[redacted]')
    .replace(/\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b/g, '[redacted]');
}
export async function readDocument(id: string): Promise<string | null> {
  if (!Object.hasOwn(DOCUMENTS, id)) return null;
  const path = DOCUMENTS[id].path;
  if ((await stat(path)).size > 256_000) throw new Error('Document exceeds the local preview limit.');
  return redact(await readFile(path, 'utf8'));
}
const targets = [
  { id: 'cognee', name: 'Local Cognee', url: 'http://127.0.0.1:8765/health', detail: 'Local API reachability only.' },
  { id: 'hydra', name: 'Local HydraDB', url: 'http://127.0.0.1:9090/readyz', detail: 'Local container readiness only.' }
];
let health: Health[] = targets.map(target => ({ ...target, status: 'unknown', checkedAt: null }));
let pending: Promise<void> | null = null;
let lastProbe = 0;
export async function probeTargets(force = false): Promise<void> {
  if (pending) return pending;
  if (!force && Date.now() - lastProbe < 60_000) return;
  pending = (async () => {
    health = await Promise.all(targets.map(async target => {
      const start = Date.now(); const checkedAt = new Date().toISOString();
      try {
        const response = await fetch(target.url, { signal: AbortSignal.timeout(6500), redirect: 'error', headers: { Accept: 'application/json' } });
        await response.body?.cancel();
        return { ...target, code: response.status, checkedAt, ms: Date.now() - start, status: response.ok ? 'up' : 'degraded' } as Health;
      } catch { return { ...target, checkedAt, ms: Date.now() - start, status: 'down', detail: 'No response within the bounded check.' } as Health; }
    }));
    lastProbe = Date.now();
  })();
  try { await pending; } finally { pending = null; }
}
export function summarizeTelemetry(input: string): { runs: Run[]; warnings: string[] } {
  const grouped = new Map<string, Run>(); const warnings: string[] = []; let malformed = 0; const lines = input.split('\n');
  for (let index = 0; index < lines.length; index++) {
    const line = lines[index].trim(); if (!line) continue;
    let event: Record<string, unknown>;
    try { event = JSON.parse(line); } catch { if (index < lines.length - 1) malformed++; continue; }
    if (typeof event.run_id !== 'string' || !/^[a-zA-Z0-9_-]{1,80}$/.test(event.run_id) || typeof event.ts !== 'number' || !Number.isFinite(event.ts)) { malformed++; continue; }
    const run = grouped.get(event.run_id) ?? { id: event.run_id, started: event.ts, ended: event.ts, events: 0, ms: 0, errors: 0, costUsd: 0, standIn: false, stages: [] };
    run.started = Math.min(run.started, event.ts); run.ended = Math.max(run.ended, event.ts); run.events++;
    if (event.ok === false || event.event === 'error') run.errors++;
    if (typeof event.cost_usd === 'number' && Number.isFinite(event.cost_usd) && event.cost_usd >= 0) run.costUsd += event.cost_usd;
    run.standIn ||= /stand.?in|fallback|local.?mode|local wave|local runner|draft.only/i.test(String(event.note ?? ''));
    if (typeof event.stage === 'string' && /^[a-zA-Z0-9_-]{1,40}$/.test(event.stage) && !run.stages.includes(event.stage)) run.stages.push(event.stage);
    run.ms = (run.ended - run.started) * 1000; grouped.set(run.id, run);
  }
  if (malformed) warnings.push(`${malformed} unreadable telemetry rows were skipped.`);
  return { runs: [...grouped.values()].sort((a, b) => b.started - a.started).slice(0, 12), warnings };
}
export async function liveSources(): Promise<Pick<Snapshot, 'health' | 'sources' | 'runs' | 'receipt' | 'machine' | 'sourceWarnings' | 'workers'>> {
  const sources = await Promise.all(Object.entries(DOCUMENTS).map(async ([id, doc]): Promise<Source> => {
    try { return { id, title: doc.title, available: true, updatedAt: (await stat(doc.path)).mtime.toISOString() }; }
    catch { return { id, title: doc.title, available: false, updatedAt: null }; }
  }));
  let freeGiB: number | null = null;
  try { const fs = await statfs('/'); freeGiB = Number((fs.bavail * fs.bsize / 1024 ** 3).toFixed(1)); } catch { /* unavailable */ }
  return { sources, runs: [], receipt: { available: false, checks: 0, passed: 0, deployed: false, at: null }, machine: { freeGiB, forge: false }, health, workers: await readWorkers(), sourceWarnings: [] };
}
