// EXPORT STUB — generated by export-judges.py. The original src/workers.ts read a private
// multi-agent monitor. The app's conversation path never uses it. currentMonitor keeps its behaviour.
import type { Snapshot } from './model.ts';
import { uptime } from 'node:os';
export function currentMonitor(value: unknown, now = Date.now(), boot = now - uptime() * 1000): boolean {
  const timestamp = typeof value === 'string' ? Date.parse(value) : NaN;
  return Number.isFinite(timestamp) && timestamp >= boot && timestamp <= now + 1000 && now - timestamp < 30000;
}
export async function readWorkers(): Promise<Snapshot['workers']> { return { generatedAt: null, lanes: [] }; }
